//
// BOTTOM NAV
export const SET_VALUE_BOTTOMNAV = "SET_VALUE_BOTTOMNAV";

//
// CATALOG
export const SET_CATALOG_SUCCESS = "SET_CATALOG_SUCCESS";

//
// MENU LIST
export const SET_MENULIST_SUCCESS = "SET_MENULIST_SUCCESS";
